name: gdgica
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  equatable: ^2.0.3 # Agrega esta línea
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_bloc: ^8.1.6
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.7.0
  http: ^1.2.1
  meta: ^1.12.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/images/speakers/
  - assets/json/

